### ISSUE TITLE
Batch: Publish the JSON schema for `devcontainer-feature.json`

### ISSUE THREAD

**Issue by joshspicer** [devcontainers/spec#140]
Context in the [`#devcontainer-community` Slack](https://github.slack.com/archives/C0431R35H37/p1668976861746579)

Similar to the `devcontainer.json` schema, publish the schema for [`devcontainer-feature.json`](https://containers.dev/implementors/features/#devcontainer-feature-json-properties).  

Supporting tools (eg: The Dev Containers VS Code extension) can then pick up this schema to provide intellisense.

## Subtasks

- [x] Publish in spec repo (https://github.com/devcontainers/spec/pull/152)
- [x] Publish on containers.dev
- [x] Embed into VS Code extension for file validation (https://github.com/microsoft/vscode-remote-containers/pull/376)
- [x] https://github.com/devcontainers/action/issues/108
